#!/bin/bash

DOTBOT_PATH="$HOME/personal/.dotbot"

# Check if Dotbot is installed, if not, clone it
if [ ! -d "$DOTBOT_PATH" ]; then
    echo "Dotbot not found. Cloning into $DOTBOT_PATH..."
    git clone --recursive https://github.com/anishathalye/dotbot.git "$DOTBOT_PATH"
fi

# Run Dotbot
"$DOTBOT_PATH/bin/dotbot" -c install.conf.yaml

